baseURL = 'https://luhaiyu.github.io/'
languageCode = 'en-us'
title = 'Grayeel 的精神角落'
theme = 'ananke'

[params]

  main_sections = ["posts","post"]
  featured_image = "/images/gohugo-default-sample-hero-image.jpg"
  description = "我的个人网站欢迎你"
